version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: core
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d demo"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: services/balance/Dockerfile
    container_name: balance-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Spring Boot datasource via environment variables
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/core
      SPRING_DATASOURCE_USERNAME: core
      SPRING_DATASOURCE_PASSWORD: core

      # Optional: tune Hibernate and SQL logging here if your app uses them
      # SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      # SPRING_JPA_SHOW_SQL: "true"

      # Optional: set active profile
      # SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    # If the app writes logs to console, this is fine; otherwise mount volumes as needed
    restart: unless-stopped

volumes:
  db_data:

networks:
  default:
    driver: bridge
