spring:
  config:
    import: optional:classpath:application-local.yaml
  application:
    name: balance
  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: core
    password: core
    driver-class-name: org.postgresql.Driver